CREATE TABLE IF NOT EXISTS log_event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    timestamp DATETIME NOT NULL,
    level VARCHAR(20) NOT NULL,
    logger VARCHAR(255) NOT NULL,
    message TEXT,
    thread VARCHAR(100),
    class_name VARCHAR(255),
    method_name VARCHAR(100),
    line_number INT,
    request_url VARCHAR(255),
    request_method VARCHAR(20),
    ip_address VARCHAR(50),
    user_id BIGINT,
    exception TEXT,
    trace_id VARCHAR(100),
    INDEX idx_timestamp (timestamp),
    INDEX idx_level (level),
    INDEX idx_user_id (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;